### ISSUE TITLE
Jedno zbiorcze issue z review aplikacji.

### ISSUE THREAD

**Issue by balkonrad** [olgac77/OCInvoice#12]
**Seller**
1. Na listview All trzeba dodać pola.
![image](https://user-images.githubusercontent.com/6885412/57509931-c776e780-7305-11e9-8929-9c41fe20dd38.png)

2. Opcja "Change Owner" na listview nie potrzebna, trzeba usunąć.
![image](https://user-images.githubusercontent.com/6885412/57510044-086efc00-7306-11e9-8014-59c9814621f8.png)

3. Lepszy rozkład pól z podziałem na sekcje Dane Selera, Dane Kontatowe, Dane bankowe, Dane systemowe
![image](https://user-images.githubusercontent.com/6885412/57510101-2dfc0580-7306-11e9-80b6-e7f3785578cf.png)

4. Usunac opcje: New Contact, New opportunity itd. jedyne co tutaj sie przyda to: Edit, Printable View, Clone, Delete

**Account**

1. Trzeba będzie uwtorzyć dedykowany lighting page dla Account'a. Tak na prawdę potrzebujemy na nim tylko podstawowych informacji + informacji adresowych.

2. Buttony i list view tak jak opisałem wyzej

**Services**
1. Listview, buttons, pages tak jak wyzej

**Invoices**
1. Listview, buttons, pages tak jak wyzej

2. Wpadł mi pomysł że invoice / service nie powinien byc edytowalny po wejsciu w statuts paid. Jesli nie mamy takiej validacji, trzeba dodac.

**Addresses**

1. Listview, buttons, pages tak jak wyzej

**VATs**
1. Listview, buttons, pages tak jak wyzej

2. Trzeba dodać zabezpieczenie przed duplikowaniem stawek (podpowiedź, na customowym polu można użyć parametru "unique").

3. Pole Value__c powinno być required moim zdanie,

**Comment by olgac77** [comment]
**"Wpadł mi pomysł że invoice / service nie powinien byc edytowalny po wejsciu w statuts paid. Jesli nie mamy takiej validacji, trzeba dodac"** - chodzi Ci tylko, żeby service na invoice nie był edytowalny czy że kazde pole na service i invoice ma byc nieedytowalne po wejsciu w status 'paid'?

**Comment by olgac77** [comment]
Dodałam do invoice walidacje, że nie zapisze zmian jesli w statusie 'Paid'. A jak to mialoby być z Service?

**Comment by balkonrad** [comment]
Jeśli invoice miałby być w statusie paid to nie można do niego także dodać service

**Comment by olgac77** [comment]
No to teraz przy dodawaniu nowego Service'u wyskakuje to:
ServiceTrigger: execution of AfterInsert caused by: System.DmlException: Update failed. First exception on row 0 with id a042p00000vCpKkAAK; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, Saving changes is not permitted. Invoice is in 'Paid' status: [] Class.NetCalculation.calculateNet: line 25, column 1 Class.ServiceTriggerHandler.afterInsert: line 14, column 1 Trigger.ServiceTrigger: line 7, column 1

Da się to ładniej wyświetlać?

**Comment by balkonrad** [comment]
Błąd jest "nie poprawny" bo jest na after insert. Jeśli chodzi o service, to na trigerze nie powinnaś pozwolić już na zapisanie, czyli walidacja powinna być na before Insert / before update.

**Comment by balkonrad** [comment]
Czyli w pseudokodzie jakbym mial to zapisac to tak:

if(isBefore){
   if(isInsert || isUpdate || isDelete){
      if('Paid'.equals(service.Invoice__r.Status)){
        thrown new Exception('Nie mozna edytowac faktury w statusie Paid');   
    }
   }

}
