### ISSUE TITLE
Unit testy

### ISSUE THREAD

**Issue by balkonrad** [olgac77/OCInvoice#15]
1. Napisać testy jednostkowe dla wszystkich klas/ triggerów w projekcie.
2. Każda z klas powinna mieć swoją dedykowaną klasę testową.
3. Minimalne pokrycie dla pojedyńczej klasy wynosić powinno **85%**
4. Testy powinny być napisane w następujący sposób:

https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_testing_testsetup_using.htm

5. Przynajmniej jeden z testów(w ramach szkolenia) powinien być napisnay z użyciem danych testowych ładowanych z pliku

https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_testing_load_data.htm

6. Podczas pisania testów powinna powstać klasa, której zadaniem dla każdego testu będzie przygotowanie danych testowych, przykład tutaj:

https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_testing_utility_classes.htm

**Comment by olgac77** [comment]
1. Napisać testy jednostkowe dla wszystkich klas/ triggerów w projekcie.
2. Każda z klas powinna mieć swoją dedykowaną klasę testową.
3. Minimalne pokrycie dla pojedyńczej klasy wynosić powinno **85%**
4. Testy powinny być napisane w następujący sposób:

https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_testing_testsetup_using.htm

5. Przynajmniej jeden z testów(w ramach szkolenia) powinien być napisnay z użyciem danych testowych ładowanych z pliku

https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_testing_load_data.htm

6. Podczas pisania testów powinna powstać klasa, której zadaniem dla każdego testu będzie przygotowanie danych testowych, przykład tutaj:

https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_testing_utility_classes.htm

**Comment by balkonrad** [comment]
Trailheady:

https://trailhead.salesforce.com/en/content/learn/modules/apex_testing

**Comment by olgac77** [comment]
Dobra, spać nie mogę, bo taka sytuacja: **Usuwanie ostatniego/jedynego service'u na invoice** - nie obsłużone. Póki co przekazujemy tylko trigger.new, w związku z tym nie można usunąć service'u nawet jeśli jest w statusie unpaid, bo wyrzuca exception(do metody przekazywana jest pusta lista). Przydałoby się chyba użyć trigger.old. Jak to najzgrabniej zrobić?

**Comment by balkonrad** [comment]
Ale miałem zonka, bo przyszło powiadomienie i myślałem że siedzisz po nocy i testy skończyłaś :D 

Ogólnie masz dobre wyczucie co trzeba zrobić.  Trigger.new jest w momencie usuwania puste. Żeby było Ci łatwiej to podsyłam POTĘŻNĄ tabelkę z rozpiską co gdzie i jak się obsługuje w trigerze

[](https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_triggers_context_variables_considerations.htm)

**Comment by olgac77** [comment]
Toś mi nie pomógł, bo do tabeli sama już wczoraj dotarłam :) chodziło mi bardziej o sposób rozpisania w kodzie, żebyś nie powiedział, ze brzydko, ze wolno, ze coś tam :)

**Comment by balkonrad** [comment]
Dać wędkę rybakowi, to źle bo chce rybę :D Rozpisz sama i zobaczymy jak to wyjdzie

**Comment by olgac77** [comment]
for (AggregateResult ar : [SELECT SUM(VAT_Amount__c) sumAmount, Invoice__c FROM Service__c WHERE Invoice__c = :**invoiceIdList** GROUP BY Invoice__c]) {
            if(ar.get('Invoice__c')!=null&&ar.get('sumAmount')!=null){
                invoiceWithVatMap.put((Id) ar.get('Invoice__c'), (Decimal) ar.get('sumAmount'));
            }
            **//tu musi być else, ale jak dostac aktualny item z invoiceIdList????**
        }

**Comment by balkonrad** [comment]
Nie za bardzo rozumiem, po co Ci else. Możesz wytłumaczyć? W tej konstrukcji nie da się zrobić else i wyciagnąć aktualny invoiceId bo przekazujesz cała listę !!!!

**Comment by olgac77** [comment]
A bo inaczej przy usunięciu ostatniego service’u nie zaktualizują sie dane na invoice, wiec muszę tu coś wstawić. Myślałam ze jest jakaś opcja.

**Comment by balkonrad** [comment]
No ale halo :) Przecież przy usuwaniu service w Trigger.old przychodzi Id Invoice. Po prostu trzeba dodać obsługę tego (teraz tylko na trigger.new wywołujemy).

**Comment by olgac77** [comment]
Moje pytanie w takim razie jak?

**Comment by balkonrad** [comment]
W ServiceTriggerHandler na afterDelete wywołujesz metody: calculateNet itd itd. Przekazujesz tam _newRecords_ które w przypadku delete jest puste. Trzeba:

1. Z poziomu triggera przekazywac trigger.old
2. Z poziomu klasy rozsrzerzyć ją tak aby odbierała "oldRecords"
3. Przeciążyć metody calculateNet itd itd.

https://javastart.pl/baza-wiedzy/programowanie-obiektowe/przeciazanie-metod

**Comment by olgac77** [comment]
Chyba będzie lepiej jak mi pokażesz o co Ci chodzi jutro

**Comment by olgac77** [comment]
InvoiceController

w metodzie getInvoice pobieram aktualny invoiceId klikając w button. Jak mogę to zrobić w metodzie testującej?

**Comment by balkonrad** [comment]
PageReference myVfPage = Page.NAZWA_PAGE;
Test.setCurrentPage(myVfPage);

// Put Id into the current page Parameters
ApexPages.currentPage().getParameters().put('invId', invoiceID);

https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_methods_system_test.htm

**Comment by olgac77** [comment]
Wiedziałam, ze odpiszesz..a myślałam ze sie nade mną zlitujesz.

**Comment by balkonrad** [comment]
tzn ?

**Comment by olgac77** [comment]
No napisałam żebyś mi nie odpisywał i pogadamy jutro :) a Ty odpisałeś.

**Comment by balkonrad** [comment]
A fakt, nie doczytałem ;)
