### ISSUE TITLE
Batch Job z przypominamie o zapłacie za fakturę

### ISSUE THREAD

**Issue by balkonrad** [olgac77/OCInvoice#24]
0. **Dodać pole "Email Sended"(checkbox) na Invoice. Jako domyślną wartość ustawić "False".**
**0a. Za pmocą DataLoader'a wykonać aktualizację już instiejących accountów w ten sposób aby każdy z nich miał Email_Sended__c = false oraz jakiś przykładowy adres email**

**0. Dodać pole Email(Email__c) na obiekcie Account.** 
0. Dodać pole do invoice wizard na pierwszy screen.

1. **Utworzyć custom object "Notify Purchaser"
Uwaga - do obiektu nie powinien być uwtorzony custom tab!!!**

**1a. Name jako autonumber z {NP-000000}**
1b. Utworzyć pole typu master - detail o nazwie "Purchaser"
**1c. Utworzyć pole formula o nazwie "Email Sended", wartość pobrać z Invoice.Email_Sended__c**
**1d. Dostęp do obiektu i pól powinien posiadać tylko system administrator (pobrać standardowy profil do repozytorium).**
1e. Dodać pole "Account Email" (Account_Email__c) -

**2 Napisać Apex Batch Job, który:
2a. Pobiera wszystkie Invoice w statusie 'Unpaid'
2b. Sprawdza czy TODAY() > Due Date
2c. Sprawdza czy Invoice.Account.Email_Sended__c = false
2d. Wstawia rekord do obiektu Notify_Purchaser__c gdzie Purchaser__c to Id z obiektu Invoice__c**
2e. Batch powinien także pobierać zawartość pola Email__c z Account u ustawiać Account_Email__c

3. Utworzyć email template (wygląd dowolny :)) oraz email alert.
Dokładne szczegóły co jest czym tutaj: 
https://help.salesforce.com/articleView?id=email_templates_landing_page.htm&type=5
https://help.salesforce.com/articleView?id=customize_wfalerts.htm&type=5

3.1 Email alert powinien jako Recipient Type korzystać z pola Account_Email__c.

4. Utworzyć Process Builder "Notify Purchaser" na obiekcie Notify_Purchaser__c 
4a. Process powinien zostać uruchomiony tylko dla nowych rekordów.
4b. Proces powinien wywoływać akcję wysyłania maila tylko wtedy kiedy Notify_Purchaser__c.Email_Sended__c = false
4b. Żeby zapobiec rekurencji(codzienne dodawanie tego samego Account'a do kolejki, proces powinien updatować pole Email_Sended__c accounta na true.

5. Utworzyć schedule job, uruchomić go na umowną godzinę ze strony Salesforce UI.

**Comment by balkonrad** [comment]
Trialheady do zrobienia:
https://trailhead.salesforce.com/en/content/learn/modules/asynchronous_apex

**Comment by olgac77** [comment]
1. Jaka treść ma być w mailu? o czym ma przypominać? Ogólnie, ze JAKIEŚ faktury są nieopłacone? Czy konkretnie?
2. Jak po zakończeniu procesu ustawie Email_Sended__c na Accouncie na true to nigdy więcej nie będę mogła wysłać do niego maila. Update po zmianie faktury na PAID? A co jeśli account ma więcej nieopłaconych faktur dla różnych sellerów?

**Comment by olgac77** [comment]
Czy z indeksowalnością picklist to jest tak, że one nie są zdefault'u indeksowane tylko Salesforce nadaje im to na podstawie performance'u?

**Comment by balkonrad** [comment]
1. Account powinien dostać konkretne przypomnienie o numerze faktury i dniu z którego pochodzi. Więc zamiast relacji do accounta zróbmy relacje do invoice i będziemy mieli wszystko. 

2. Słusznie, nanieś proszę zmiany wyżej. 

3. Tak ale to kolejny warunek który powinien być sprawdzany w execute. 

4. Tak jak piszesz i jak ci mówiłem, będzie tym zarządzał query optymizer ale jest to zalecane podejście przy zapytaniach.

**Comment by olgac77** [comment]
1. Nie widzę akcji w Process Builderze, która wysyła maila. Jest tylko taka, która wysyła Email Alert. Chyba, że czegoś nie widzę
2. Zaczynając proces of Notify_Purchaser__c nie mogę zakończyć procesu na update Invoice__c - chyba, że coś źle klikam.

**Comment by balkonrad** [comment]
1. Tak wysyła się email alert który wysyła email template.
2.  Trzeba sposobem :D 

![PB](https://user-images.githubusercontent.com/6885412/64922950-0eee1280-d7d5-11e9-9265-066fbf2f67a9.gif)
